### PR TITLE
Refactor vandalism detection package

### PR DESCRIPTION
**Pull request by GezimSejdiu**
This PR does a cleanup and refactor the vandalism detection package. It introduces a common layer for feature extractions since it is done on the string manipulation only and can be used further by Spark and Flink module.

Best regards,

### CODE REVIEW

**Comment by dgraux** [comment]
Hello @GezimSejdiu 
Thank you very much. Are you also considering adding a test `SANSA-ML/sansa-ml-spark/src/test/scala/net/sansa_stack/ml/spark/outliers/`?

**Review by dgraux — APPROVED** [review]
Hey @GezimSejdiu 
Thank you very much for your contribution! Indeed, having a common layer for feature extractions is really an interesting factorization.
I approve these changes for a merge. :+1:

**Comment by GezimSejdiu** [comment]
Hi @dgraux ,
indeed. Will consider adding basic unit-test for the vandalism detection methods.

Best,

**Review by dgraux — APPROVED** [review]
Hi @GezimSejdiu 
Thank you very much for the unit-test addition.

**Pull request merged**
